---
extends: airbnb
parser: babel-eslint
env:
  browser: false
  node: true
rules:
  strict: 0
  "react/jsx-no-bind": 1
  "react/sort-comp": [
    2,
    {
        order: [
            'static-methods',
            'lifecycle',
            'everything-else',
            'render'
        ],
        groups: {
            lifecycle: [
                'displayName',
                'props',
                'propTypes',
                'contextTypes',
                'childContextTypes',
                'mixins',
                'statics',
                'defaultProps',
                'constructor',
                'getDefaultProps',
                'getInitialState',
                'state',
                'getChildContext',
                'componentWillMount',
                'componentDidMount',
                'componentWillReceiveProps',
                'shouldComponentUpdate',
                'componentWillUpdate',
                'componentDidUpdate',
                'componentWillUnmount'
            ]
        }
    }
]
