vscode:
  extensions:
    - oderwat.indent-rainbow
    - mintlify.document
    - streetsidesoftware.code-spell-checker
    - tombonnike.vscode-status-bar-format-toggle
    - github.copilot
    - fivepointseven.node-version
    - kejun.devtoys
    - esbenp.prettier-vscode
    - visualstudioexptteam.vscodeintellicode
    - styled-components.vscode-styled-components
    - kejun.devtoys
    - naumovs.color-highlight
