stages:
  - build-develop

build_package:
  stage: build-develop
  image: alpine:latest
  tags:
    - docker-exec
  before_script:
    - apk add yarn
  script:
    - yarn install
    - yarn build:dev
  artifacts:
    paths:
      - dist/
  only:
   - develop