stages:
  - build-develop
  - build-prod

build_package:
  stage: build-develop
  image: alpine:latest
  tags:
    - docker-exec
  before_script:
    - apk add yarn
  script:
    - yarn install
    - yarn build:dev
  artifacts:
    paths:
      - dist/
  only:
   - develop
   
build_prod_package:
  stage: build-prod
  image: alpine:latest
  tags:
    - docker-exec
  before_script:
    - apk add yarn
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
  only:
   - "4.0"