stages:
  - build
  - deploy

build_develop:
  stage: build
  image: alpine:latest
  only:
    - merge_requests
    - develop
  tags:
    - docker-exec
  artifacts:
    paths:
      - build/
  before_script:
    - apk add yarn
  script:
    - mkdir develop_build
    - cd develop_build
    - yarn install
    - yarn build:dev

build_5_1:
  stage: build
  image: alpine:latest
  only:
    - develop
  tags:
    - docker-exec
  artifacts:
    paths:
      - build/
  before_script:
    - apk add yarn
  script:
    - mkdir 5_1_build
    - cd 5_1_build
    - yarn install
    - yarn build

upload_build:
  stage: deploy
  image: alpine:latest
  only:
    - develop
  tags:
    - docker-exec
  dependencies:
    - build_develop
    - build_5_1
  script:
    - apk add zip openssh-client
    - mkdir -p ~/.ssh
    - echo "${DEPLOY_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - echo "${DEPLOY_PUBKEY}" > ~/.ssh/id_rsa.pub
    - echo "${DEPLOY_PRIVKEY}" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/id_rsa.pub ~/.ssh/known_hosts

    - find build -name \*.gz | while read a; do n=`echo $a|sed s/\.gz$//`; if [ -f $n ]; then rm $n; fi; done

    - mkdir -p ./develop/webapp
    - mv -f develop_build/build/* ./develop/webapp/
    - zip -r qorus-webapp-develop.zip develop
    - scp qorus-webapp-develop.zip ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/

    - mkdir -p ./5_1/webapp
    - mv -f 5_1_build/build/* ./5_1/webapp/
    - zip -r qorus-webapp-5_1.zip 5_1
    - scp qorus-webapp-5_1.zip ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PATH}/
