const INTERFACE_ICONS = {
  workflows: 'exchange',
  workflow: 'exchange',
  jobs: 'calendar',
  job: 'calendar',
  services: 'merge-links',
  service: 'merge-links',
  groups: 'group-objects',
  group: 'group-objects',
  alerts: 'warning-sign',
  alert: 'warning-sign',
  remote: 'globe',
  remotes: 'globe',
  datasource: 'join-left',
  datasources: 'join-left',
  user: 'people',
  'user-connection': 'people',
  users: 'people',
  role: 'settings',
  roles: 'settings',
  sla: 'time',
  slas: 'time',
  valuemap: 'map',
  valuemaps: 'map',
  'value maps': 'map',
  'value map': 'map',
  vmap: 'map',
  vmaps: 'map',
  mapper: 'diagram-tree',
  mappers: 'diagram-tree',
  order: 'box',
  orders: 'box',
  error: 'error',
  errors: 'error',
};

const INTERFACE_ID_KEYS: Array<string> = [
  'workflowid',
  'mapperid',
  'serviceid',
  'roleid',
  'jobid',
  'alertid',
];

const INTERFACE_IDS: any = {
  workflows: 'workflowid',
  workflow: 'workflowid',
  services: 'serviceid',
  service: 'serviceid',
  jobs: 'jobid',
  job: 'jobid',
  vmaps: 'id',
  vmap: 'id',
  mappers: 'mapperid',
  mapper: 'mapperid',
  fsms: 'fsm',
  pipelines: 'pipeline',
};

const INTERFACE_ID_LINKS: any = {
  workflow: '/workflow/',
  workflows: '/workflows?paneId=',
  services: '/services?paneId=',
  service: '/service/',
  job: '/job/',
  jobs: '/jobs?paneId=',
  mapper: '/mappers/',
  mappers: '/mappers/',
  role: '/rbac?tab=roles&search=',
  valuemap: '/valuemaps?paneId=',
  vmap: '/valuemaps?paneId=',
  valuemaps: '/valuemaps?paneId=',
  vmaps: '/valuemaps?paneId=',
  'value maps': '/valuemaps?paneId=',
  'value map': '/valuemaps?paneId=',
};

export { INTERFACE_ICONS, INTERFACE_ID_KEYS, INTERFACE_ID_LINKS, INTERFACE_IDS };
