const INTERFACE_ICONS = {
  workflows: 'exchange',
  workflow: 'exchange',
  jobs: 'calendar',
  job: 'calendar',
  services: 'merge-links',
  service: 'merge-links',
  groups: 'group-objects',
  group: 'group-objects',
  alerts: 'warning-sign',
  alert: 'warning-sign',
  remote: 'globe',
  remotes: 'globe',
  datasource: 'join-left',
  datasources: 'join-left',
  user: 'people',
  ['user-connection']: 'people',
  users: 'people',
  sla: 'time',
  slas: 'time',
  valuemap: 'map',
  valuemaps: 'map',
  mapper: 'diagram-tree',
  mappers: 'diagram-tree',
};

export { INTERFACE_ICONS };
