---
env:
  browser: true
  commonjs: true
  node: false
rules:
  strict:
    - 2
    - never
globals:
  process:
    env:
      NODE_ENV: 'production'
  Generator: true
  SyntheticEvent: true
  KeyboardEvent: true
  EventHandler: true
  document: true
  window: true
  localStorage: true
  WebSocket: true
