name: Pull Request Tests
on:
  pull_request:
    branches: [develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        id: install_modules
        run: yarn
      - name: Install Playwright Browsers
        id: setup_tests
        run: yarn setup-test
      - name: Start server and run Playwright tests
        id: run_server_and_tests
        run: |
          yarn start:ci &
          sleep 30 &&
          curl -k https://localhost:3000 &&
          TEST_USER=${{ secrets.TEST_USER }} TEST_USER_PASS=${{ secrets.TEST_USER_PASS }} yarn test:ci
      - uses: actions/upload-artifact@v3
        id: upload_artifacts
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Slack notification
        id: notify_slack
        uses: Foxhoundn/slack@v1.2.94
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: Qorus UI
